package vista;

import controlador.ControladorPrincipal;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import modelo.Concierto;

import controlador.ControladorConcierto;

public class FrmConcierto extends javax.swing.JFrame {
    
    // Variables para respetar el flujo MVC
    private ControladorConcierto controladorConcierto;
    private javax.swing.JFrame vistaAnterior;
    private Concierto conciertoAEditar;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmConcierto.class.getName());

    // Modificamos el constructor para recibir el controlador y la ventana anterior
    public FrmConcierto(ControladorPrincipal ctrl, javax.swing.JFrame vistaAnterior) {
        this.controladorConcierto = new ControladorConcierto(this, ctrl);
        this.vistaAnterior = vistaAnterior;
        initComponents();
        this.setLocationRelativeTo(null); // Centrar la ventana
    }

    // Nuevo constructor para edición/reconfiguración
    public FrmConcierto(ControladorPrincipal ctrl, javax.swing.JFrame vistaAnterior, Concierto conciertoAEditar) {
        this.controladorConcierto = new ControladorConcierto(this, ctrl);
        this.vistaAnterior = vistaAnterior;
        this.conciertoAEditar = conciertoAEditar;
        initComponents();
        this.setLocationRelativeTo(null);

        // Pre-poblamos los campos de texto y bloqueamos edición
        txtNombre.setText(conciertoAEditar.getNombre());
        txtFecha.setText(conciertoAEditar.getFecha().toString());
        txtNombre.setEditable(false); 
        txtFecha.setEditable(false);
        btnGuardar.setText("Reconfigurar Zonas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        jLabel1.setText("Ingresa fecha: ");

        jLabel2.setText("Ingresa nombre:");

        jLabel3.setText("Concierto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnGuardar)
                        .addGap(51, 51, 51))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (this.vistaAnterior != null) {
            this.vistaAnterior.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (conciertoAEditar != null) {
            // MODO EDICIÓN
            try {
                controladorConcierto.prepararReconfiguracionZonas(conciertoAEditar);
                ejecutarBucleZonas();

                if (this.vistaAnterior != null) {
                    if (this.vistaAnterior instanceof FrmAdmin) {
                        ((FrmAdmin) this.vistaAnterior).refrescarTabla();
                    }
                    this.vistaAnterior.setVisible(true);
                }
                this.dispose();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Edición", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // MODO CREACIÓN
            String nombre = txtNombre.getText().trim();
            String fechaStr = txtFecha.getText().trim();

            // Delegar la validación y el registro al controlador
            boolean exitoRegistro = controladorConcierto.registrarNuevoConcierto(nombre, fechaStr);
            if (!exitoRegistro) {
                return;
            }

            ejecutarBucleZonas();

            if (this.vistaAnterior != null) {
                if (this.vistaAnterior instanceof FrmAdmin) {
                    ((FrmAdmin) this.vistaAnterior).refrescarTabla();
                }
                this.vistaAnterior.setVisible(true);
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void ejecutarBucleZonas() {
        String numZonasStr = javax.swing.JOptionPane.showInputDialog(this, "¿Cuántas zonas tendrá este concierto?");
        if (numZonasStr != null && !numZonasStr.trim().isEmpty()) {
            try {
                int numZonas = Integer.parseInt(numZonasStr.trim());
                for (int i = 0; i < numZonas; i++) {
                    String nombreZona = javax.swing.JOptionPane.showInputDialog(this, "Nombre de la zona " + (i + 1) + " (Ej: VIP):");
                    if (nombreZona == null) break;

                    String cap = javax.swing.JOptionPane.showInputDialog(this, "Capacidad total para " + nombreZona + ":");
                    if (cap == null) break;

                    String prec = javax.swing.JOptionPane.showInputDialog(this, "Precio (S/) para " + nombreZona + ":");
                    if (prec == null) break;

                    // El controlador valida y agrega la zona
                    boolean exitoZona = controladorConcierto.agregarZonaAlConcierto(nombreZona, cap, prec);
                    if (!exitoZona) {
                        i--; // Reintentar la misma zona si falló la validación
                    }
                }
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Número de zonas inválido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
