/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.ControladorPrincipal;
/**
 *
 * @author alex_
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    private ControladorPrincipal ctrl;
    public FrmMenuPrincipal(ControladorPrincipal ctrl) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ctrl = ctrl;
        cargarDatosCliente();
        
    }
    private void cargarDatosCliente() {
        modelo.Persona usuario = ctrl.getUsuarioLogueado();
        if (usuario != null) {
            lblBienvenida.setText("Bienvenido: " + usuario.getNombres() + " " + usuario.getApellidos());
            
            if (usuario instanceof modelo.Cliente) {
                modelo.Cliente c = (modelo.Cliente) usuario;
                lblPuntos.setText("Puntos: " + c.getPuntos());
            } else {
                lblPuntos.setText("Puntos: N/A");
                lblConcierto.setText("Administración");
            }
            
            cbxConcierto.removeAllItems();
            for (modelo.Concierto con : ctrl.getTodosLosConciertos()) {
                cbxConcierto.addItem(con);
            }
            
            if (ctrl.getConciertoSeleccionado() != null) {
                cbxConcierto.setSelectedItem(ctrl.getConciertoSeleccionado());
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        lblBienvenida = new javax.swing.JLabel();
        btnVerZonas = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        btnMisCompras = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblPuntos = new javax.swing.JLabel();
        lblConcierto = new javax.swing.JLabel();
        cbxConcierto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(new java.awt.GridBagLayout());

        lblBienvenida.setText("Bienvenido:");

        btnVerZonas.setText("Ver zonas y precios");
        btnVerZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerZonasActionPerformed(evt);
            }
        });

        btnComprar.setText("Comprar Entradas");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnMisCompras.setText("Mi Historial y Puntos");
        btnMisCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisComprasActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        lblPuntos.setText("Puntos:");

        lblConcierto.setText("Seleccione el concierto:");

        cbxConcierto.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbxConcierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxConciertoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(lblConcierto)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprar)
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnVerZonas))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblBienvenida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPuntos)
                        .addGap(30, 30, 30)))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMisCompras)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnCerrarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenida)
                    .addComponent(lblPuntos))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConcierto)
                        .addComponent(cbxConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerZonas)
                    .addComponent(btnComprar))
                .addGap(18, 18, 18)
                .addComponent(btnMisCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        FrmCliente cliente = new FrmCliente(this.ctrl);
        cliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        ctrl.cerrarSesion();
        FrmLogin login = new FrmLogin(this.ctrl);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVerZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerZonasActionPerformed
        if (ctrl.getConcierto() != null) {
            StringBuilder sb = new StringBuilder("Zonas del Concierto: " + ctrl.getConcierto().getNombre() + "\n\n");
            for (modelo.Zona z : ctrl.getConcierto().getTodasLasZonas()) {
                sb.append("- ").append(z.getNombre())
                  .append(": S/ ").append(z.getPrecio())
                  .append(" (Disponibles: ").append(z.getCapacidadDisponible()).append("/").append(z.getCapacidadTotal()).append(")\n");
            }
            javax.swing.JOptionPane.showMessageDialog(this, sb.toString());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay concierto seleccionado.");
        }
    }//GEN-LAST:event_btnVerZonasActionPerformed

    private void btnMisComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisComprasActionPerformed
        modelo.Persona usuario = ctrl.getUsuarioLogueado();
        if (usuario instanceof modelo.Cliente) {
            modelo.Cliente c = (modelo.Cliente) usuario;
            StringBuilder sb = new StringBuilder("Historial de Compras de " + c.getNombres() + "\n");
            sb.append("Puntos acumulados: ").append(c.getPuntos()).append("\n\n");
            sb.append("Compras realizadas:\n");
            
            boolean tieneVentas = false;
            for (modelo.Concierto con : ctrl.getTodosLosConciertos()) {
                for (modelo.Venta v : con.getTodasLasVentas()) {
                    if (v.getCliente().getDni().equals(c.getDni())) {
                        sb.append("- ").append(con.getNombre())
                          .append(" | ").append(v.getZona().getNombre())
                          .append(" | Cantidad: ").append(v.getCantidadEntradas())
                          .append(" | Total: S/ ").append(v.getMonto())
                          .append(" | Transacción: ").append(v.getIdTransaccion()).append("\n");
                        tieneVentas = true;
                    }
                }
            }
            if (!tieneVentas) {
                sb.append("No has realizado ninguna compra todavía.");
            }
            javax.swing.JOptionPane.showMessageDialog(this, sb.toString());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Esta opción solo está disponible para Clientes.");
        }
    }//GEN-LAST:event_btnMisComprasActionPerformed

    private void cbxConciertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxConciertoActionPerformed
        modelo.Concierto seleccion = (modelo.Concierto) cbxConcierto.getSelectedItem();
        if (seleccion != null) {
            ctrl.setConciertoSeleccionado(seleccion);
        }
    }//GEN-LAST:event_cbxConciertoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnMisCompras;
    private javax.swing.JButton btnVerZonas;
    private javax.swing.JComboBox<modelo.Concierto> cbxConcierto;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblConcierto;
    private javax.swing.JLabel lblPuntos;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
