/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.ControladorPrincipal;
/**
 *
 * @author alex_
 */
public class FrmTarjeta extends javax.swing.JFrame {
    private ControladorPrincipal ctrl;
    private FrmCliente vistaCliente;
    /**
     * Creates new form FrmTarjeta
     */
    public FrmTarjeta(ControladorPrincipal ctrl, FrmCliente vistaCliente) {
        this.ctrl = ctrl;
        this.vistaCliente = vistaCliente;
        initComponents();
        this.setLocationRelativeTo(null);
        modelo.Persona usuario = ctrl.getUsuarioLogueado();
        if (usuario != null) {
            lblRegistraNombre.setText("Registrar tu tarjeta, " + usuario.getNombres());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblNumTarjeta = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblVencimiento = new javax.swing.JLabel();
        lblCvv = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();
        txtNombreTarjeta = new javax.swing.JTextField();
        txtFechaVencimiento = new javax.swing.JTextField();
        txtCvv = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        CheckTarjeta = new javax.swing.JCheckBox();
        lblRegistraNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumTarjeta.setText("Numero Tarjeta:");

        lblNombre.setText("Nombre Titular:");

        lblVencimiento.setText("Fecha Vencimiento:");

        lblCvv.setText("CVV");

        txtNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTarjetaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar Tarjeta");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        CheckTarjeta.setText("Guardar tarjeta para futuras compras");
        CheckTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVolver)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNumTarjeta)
                                .addComponent(lblNombre)
                                .addComponent(lblVencimiento)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(lblCvv))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumeroTarjeta)
                                    .addComponent(txtNombreTarjeta)
                                    .addComponent(txtFechaVencimiento)
                                    .addComponent(txtCvv, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnGuardar)
                                .addGap(0, 45, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(CheckTarjeta)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumTarjeta)
                    .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombreTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVencimiento)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCvv)
                    .addComponent(txtCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        lblRegistraNombre.setText("Registrar tu tarjeta, [nombre]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblRegistraNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblRegistraNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTarjetaActionPerformed
        
    }//GEN-LAST:event_txtNumeroTarjetaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (this.vistaCliente != null) {
            this.vistaCliente.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String nroTarjeta = txtNumeroTarjeta.getText().trim().replaceAll("\\s+", "");
        String titular = txtNombreTarjeta.getText().trim();
        String vencimiento = txtFechaVencimiento.getText().trim();
        String cvvStr = txtCvv.getText().trim();
        boolean guardarFuturas = CheckTarjeta.isSelected();
        
        if (nroTarjeta.isEmpty() || titular.isEmpty() || vencimiento.isEmpty() || cvvStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!nroTarjeta.matches("\\d{13,19}")) { 
            javax.swing.JOptionPane.showMessageDialog(this, "El número de tarjeta debe tener entre 13 y 19 dígitos numéricos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int cvv = 0;
        try {
            cvv = Integer.parseInt(cvvStr);
        } catch(NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El CVV debe ser únicamente numérico.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        

        modelo.Tarjeta nuevaTarjeta = new modelo.Tarjeta(nroTarjeta, titular, vencimiento, cvv);
        
        if (guardarFuturas) {
            modelo.Persona usuario = ctrl.getUsuarioLogueado();
            if (usuario instanceof modelo.Cliente) {
                modelo.Cliente cliente = (modelo.Cliente) usuario;
                cliente.setTarjeta(nuevaTarjeta);
            }
        }
        
        if (this.vistaCliente != null) {
            this.vistaCliente.setTarjetaActiva(nuevaTarjeta);
            this.vistaCliente.setVisible(true);
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Tarjeta registrada correctamente.");
        this.dispose();
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void CheckTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckTarjetaActionPerformed
        
    }//GEN-LAST:event_CheckTarjetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckTarjeta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCvv;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumTarjeta;
    private javax.swing.JLabel lblRegistraNombre;
    private javax.swing.JLabel lblVencimiento;
    private javax.swing.JTextField txtCvv;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtNombreTarjeta;
    private javax.swing.JTextField txtNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
